Document: lsdfailtools-web
Title: Debian lsdfailtools-web Manual
Author: <insert document author here>
Abstract: This manual describes what lsdfailtools-web is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/lsdfailtools-web/lsdfailtools-web.sgml.gz

Format: postscript
Files: /usr/share/doc/lsdfailtools-web/lsdfailtools-web.ps.gz

Format: text
Files: /usr/share/doc/lsdfailtools-web/lsdfailtools-web.text.gz

Format: HTML
Index: /usr/share/doc/lsdfailtools-web/html/index.html
Files: /usr/share/doc/lsdfailtools-web/html/*.html
